apiVersion: v2
name: cluster-proportional-autoscaler
version: 1.1.0
appVersion: 1.8.6
description: This chart is used to deploy an instance of the cluster-proportional-autoscaler.
maintainers:
  - name: krmichel
    url: https://github.com/krmichel
  - name: d-mcd
    url: https://github.com/d-mcd
